name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "running the test operation"

  build-and-push-docker-image:
    name: Build Docker image and push to registry

    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker build
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:

          context: .

          tags: |
            prajapatdip/youtube:${{ github.run_number }}
            ghcr.io/prajapatdip/youtube:${{ github.run_number }}

          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: prajapatdip/YouTubeCloneMenifest
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "${{ secrets.G_EMAIL }}"
          git config --global user.name "prajapatdip"
          echo ${{ github.sha }}
          sed -i "s/${{ github.actor }}.*/${{ github.actor }}\/youtube:${{ github.run_number }}/" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.run_number }}"
      - run: echo ${{ github }}
      - run: git push origin master
